import ReactQueryProvider from "../../lib/tanstack-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-arial antialiased" cz-shortcut-listen="true">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
